apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend

spec:
  selector:
    matchLabels:
      module: backend

  template:
    metadata:
      labels:
        module: backend

    spec:
      containers:
        - name: backend
          image: backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
