apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  # replicas: 1

  selector:
    matchLabels:
      module: backend

  template:
    metadata:
      name: backend
      labels:
        module: backend

    spec:
      containers:
        - name: backend
          image: coolapp-backend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
