apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      name: backend
      labels:
        app: backend

    spec:
      containers:
        - name: app
          image: backend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
