apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
spec:
  schedule: "* * * * *"
  suspend: true

  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: frontend
              image: backend:v1
              command: ["python", "backup.py"]
              imagePullPolicy: IfNotPresent
          restartPolicy: Never
