apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    module: frontend

  ports:
    # freiwillig wählbar
    - port: 81
      # container port
      targetPort: 80
      nodePort: 32050

  type: NodePort
