apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  selector:
    matchLabels:
      app-frontend: frontend-value

  template:
    metadata:
      name: frontend
      labels:
        app-frontend: frontend-value

    spec:
      containers:
        - name: app
          image: frontend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "50Mi"
              cpu: "100m"
