apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    module: frontend

  ports:
    # freiwillig wählbar -> http://{service_name}:{port} z.b http://frontend:80
    - port: 80
      # container port
      targetPort: 5000
      # node port (extern, nur bei NodePort)
      nodePort: 32500

  type: NodePort
