apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app-frontend: frontend-value

spec:
  containers:
    - name: app
      image: app-frontend:latest
      ports:
        - containerPort: 80
