apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: frontend

spec:
  selector:
    matchLabels:
      app-frontend: frontend-value

  template:
    metadata:
      name: frontend
      labels:
        app-frontend: frontend-value

    spec:
      containers:
        - name: app
          image: app-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
