apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  selector:
    matchLabels:
      module: frontend

  template:
    metadata:
      labels:
        module: frontend

    spec:
      containers:
        - name: frontend
          image: frontend:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

          volumeMounts:
            - name: app-storage-disk
              mountPath: /data

      volumes:
        - name: app-storage-disk
          persistentVolumeClaim:
            claimName: app-storage
