apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  selector:
    matchLabels:
      app-frontend: frontend-value

  template:
    metadata:
      name: frontend
      labels:
        app-frontend: frontend-value

    spec:
      containers:
        - name: app
          image: frontend:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "50Mi"
              cpu: "100m"

          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret

          # readinessProbe:
          #   exec:
          #     command:
          #       - echo
          #       - ok
          #   initialDelaySeconds: 5
          #   periodSeconds: 3

          # livenessProbe:
          #   exec:
          #     command:
          #       - echo
          #       - ok
          #   initialDelaySeconds: 5
          #   periodSeconds: 3

          volumeMounts:
            - name: app-storage-disk
              mountPath: /data

      volumes:
        - name: data-disk
          hostPath:
            path: /tmp/data-disk

        - name: app-storage-disk
          persistentVolumeClaim:
            claimName: app-storage
