apiVersion: batch/v1
kind: Job
metadata:
  name: hello

spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: frontend
          image: backend:v1
          command: ["python", "backup.py"]
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
