apiVersion: v1
kind: Pod
metadata:
  name: frontend2
  labels:
    module: frontend

spec:
  containers:
    - name: frontend
      image: coolapp-frontend:v1
      ports:
        - containerPort: 5000
