version: "3.8"

services:
  frontend:
    container_name: frontend
    image: coolapp-frontend:v1
    build:
      context: frontend
      args:
        - module=backendtest
        - version=3.0
    ports:
      - ${FE_EXTERN_PORT}:${FE_INTERN_PORT}
    volumes:
      - ./frontend:/frontend
    environment:
      - FRONTEND_PORT=${FE_INTERN_PORT}
      - BACKEND_URL=http://backend:${BE_INTERN_PORT}

    env_file:
      - ./frontend/test.env
    networks:
      - frontend-network

  backend:
    container_name: backend
    image: coolapp-backend:v1
    build: backend
    ports:
      - 81:80
    volumes:
      - ./backend:/backend
      - user_data:/abc
    networks:
      - db-network
      - frontend-network

  web:
    container_name: web
    image: httpd
    ports:
      - 9000:80
    volumes:
      - ./web:/usr/local/apache2/htdocs/
    networks:
      - frontend-network

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - db-network
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8090:8080
    networks:
      - db-network

networks:
  frontend-network:
  db-network:

volumes:
  db_data:
  user_data:
    external: true
  test_data:
