services:
  frontend:
    image: frontend:v1
    build:
      context: frontend
      dockerfile: app.Dockerfile
      args:
        - version=10
    ports:
      - ${FE_PORT}:80

    environment:
      - APP_SECRET=${FRONTEND_SECRET}

    networks:
      - secret-network

    volumes:
      - ./frontend:/app

  backend:
    image: backend:v1
    build: backend
    ports:
      - ${BE_PORT}:80

    networks:
      - secret-network

    volumes:
      - ./backend:/app

networks:
  secret-network:
