version: "3.8"

services:
  frontend:
    build: ../frontend
    entrypoint: python frontend.py
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - ../frontend:/frontend
      - user_data:/data
    networks:
      - frontend-network

    env_file:
      - ../frontend/.env

  backend:
    container_name: backend
    build: ../backend
    command: python frontend.py
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - ../backend:/backend
      - user_data:/data
    networks:
      - frontend-network
      - db-network

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db-network

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8090:8080
    networks:
      - db-network

volumes:
  db_data:
  user_data:

networks:
  frontend-network:
    driver: bridge

  db-network:
    driver: bridge
