apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-storage
  labels:
    module: app
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
