apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    module: frontend
spec:
  containers:
    - name: frontend
      image: frontend:v1
      imagePullPolicy: Never
      ports:
        - containerPort: 80

      readinessProbe:
        exec:
          command:
            - cat
            - /test/sadsadas
        initialDelaySeconds: 5
        periodSeconds: 3
