apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend

spec:
  selector:
    matchLabels:
      module: frontend

  template:
    metadata:
      labels:
        module: frontend

    spec:
      containers:
        - name: frontend
          image: frontend:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
