apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    tier: backend

spec:
  selector:
    matchLabels:
      tier: backend

  template:
    metadata:
      labels:
        tier: backend

    spec:
      containers:
        - name: backend
          image: backend:v1
          ports:
            - containerPort: 80

          resources:
            limits:
              cpu: "100m"
              memory: "40Mi"
